# Generated by Django 6.0.2 on 2026-03-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_planimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decorplan',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
