# Generated by Django 6.0.3 on 2026-03-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_alter_decorplan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decorplan',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='planimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
