# Generated by Django 6.0.3 on 2026-03-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0006_alter_decorplan_image_alter_planimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('in_progress', 'In Progress')], default='pending', max_length=12),
        ),
    ]
