# Generated by Django 6.0.3 on 2026-04-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0008_addevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddEvent',
        ),
    ]
